ci(build-kernel): Refactor workflow

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -1,4 +1,5 @@
-name: Build kernel and integrate KSU Next via Kprobes
+name: Build
+run-name: Build kernel & integrate `stable` KernelSU Next via Kprobes
 on:
   workflow_dispatch:
 
@@ -6,13 +7,16 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4
+      - name: Clone source
+        uses: actions/checkout@v6
+        with:
+          ref: ksun-stable-kprobes  # Use the relevant branch
+          fetch-depth: '1'
 
       - name: Set up the toolchain
         run: |
           sudo apt update
-          sudo apt install -y \
+          sudo apt install -y --no-install-recommends \
             bc bison build-essential curl flex \
             g++-multilib gcc-multilib git gnupg \
             lib32readline-dev lib32z1-dev \
@@ -20,37 +24,37 @@ jobs:
             lzop zlib1g-dev pahole dwarves cpio zip \
             python3 python-is-python3 tar perl lz4 jq
 
-      - name: Clone source
-        run: |
-          git clone --depth=1 -b kprobes https://github.com/reddxae/kernel_samsung_sm8550-common-ksu.git
-
-          # Clone only necessary version of the AOSP Clang (critically saves time and free space!)
-          curl -L -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/ebcc6c3bef363bc539ea39f45b6abae1dce6ff1a/clang-r574158.tar.gz
-          mkdir clang
-          tar -xf clang.tar.gz -C clang
+          # The AOSP Clang version currently in use is r574158
+          curl -sSfL --retry 3 --connect-timeout 10 \
+            -o clang.tar.gz \
+            "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/mirror-goog-main-llvm-toolchain-source/clang-r574158.tar.gz" || \
+            { echo "ERROR: Failed to download AOSP Clang! Aborting."; exit 1; }
+          mkdir clang-toolchain
+          tar -xf clang.tar.gz -C clang-toolchain
           rm clang.tar.gz
 
       - name: Integrate KernelSU Next
         run: |
-          cd kernel_samsung_sm8550-common-ksu
+          # Integrate the KernelSU Next stable branch into the source
+          (curl -sSfL --retry 3 --connect-timeout 5 \
+            "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/stable/kernel/setup.sh" || \
+            { echo "ERROR: Failed to retrieve the KernelSU Next setup script! Aborting." >&2; exit 1; }) | \
+            bash -s stable
+
+          # Filename will include the release tag, since the stable branch normally updates prior to a new release
 
           # Determine the tag of the latest release of KernelSU Next
-          echo "KSU_VERSION=$(curl -s "https://api.github.com/repos/KernelSU-Next/KernelSU-Next/tags" | jq -r '.[0].name')" >> $GITHUB_ENV
-
-          # Integrate the latest stable KernelSU Next into the source
-          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/stable/kernel/setup.sh" | bash -s stable
+          echo "KSU_TAG=$(awk -F/ '/tags/ {print $NF}' KernelSU-Next/.git/packed-refs | tail -1)" >> $GITHUB_ENV
 
       - name: Set up swap space
         uses: pierotofy/set-swap-space@master
         with:
           swap-size-gb: 16
 
-      - name: Build the kernel
+      - name: Compile the kernel
         run: |
           # Add AOSP Clang to local PATH
-          export PATH="$(pwd)/clang/bin:$PATH"
-
-          cd kernel_samsung_sm8550-common-ksu
+          export PATH="$GITHUB_WORKSPACE/clang-toolchain/bin:$PATH"
 
           # Determine the current kernel version
           echo "KERNEL_VERSION=$(make kernelversion | awk '/^[0-9]/ {print $1}')" >> $GITHUB_ENV
@@ -61,17 +65,17 @@ jobs:
           # Generate configuration
           make -j$(nproc --all) O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 gki_defconfig || exit 1
 
-          # Run build
+          # Run make
           make -j$(nproc --all) O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 || exit 1
 
-      - name: Package image with AnyKernel3
+      - name: Package image with AnyKernel3  # Avoid zipping, as `upload-artifact` handles compression automatically
         run: |
-          cp kernel_samsung_sm8550-common-ksu/.github/goodies/AnyKernel3.zip .
+          cp .github/goodies/AnyKernel3.zip .
           unzip AnyKernel3.zip -d AnyKernel3/
-          cp kernel_samsung_sm8550-common-ksu/out/arch/arm64/boot/Image.gz AnyKernel3/
+          cp out/arch/arm64/boot/Image.gz AnyKernel3/
 
       - name: Upload the flashable kernel
         uses: actions/upload-artifact@v4
         with:
-          name: common-${{ env.KERNEL_VERSION }}_ksunext-${{ env.KSU_VERSION }}_${{ env.DATE }}
+          name: common-${{ env.KERNEL_VERSION }}_ksun-${{ env.KSU_TAG }}-kprobes_${{ env.DATE }}
           path: AnyKernel3/
